### ISSUE TITLE
question ui: Having no questions crashes the server

### ISSUE THREAD

**Issue by derwild** [Party-Hats/Dota-Quiz-Twitch-Bot#34]

**Comment by N4ppo** [comment]
I am trying to work on this. As I see it, there is a design decision to be made first:
**Should the bot be able to run without any questions?**
If **yes**, we need all our functions to handle 0-size arrays of questions. If **no**, we can simply throw an error during initialization.
Which do you prefer?

**Comment by derwild** [comment]
I don't really see the use case to have 0 questions at the moment. 
I think an error at startup, that stops the bot from running at all and some way of removing the ability to delete all questions in the ui should be good enough for now
